version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: employee_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped
  backend:
    build: .
    container_name: employee_backend
    env_file:
      - ./.env
    environment:
      PORT: 3001
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy


  caddy:
    image: caddy:2-alpine
    container_name: employee_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  pg_data:
  caddy_data:
  caddy_config:
