version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: employee_postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped
  backend:
    build: .
    container_name: employee_backend
    env_file:
      - ./.env
    environment:
      PORT: 3001
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  spring_api:
      image: jifrozen0110/attendance-spring:stage
      environment:
        SPRING_PROFILES_ACTIVE: stage
        # DB는 compose 네트워크에서 서비스명으로 접근
        DATABASE_URL: jdbc:postgresql://mydreamday:mydreamday0503%21@127.0.0.1:5432/attendance_stage?schema=mdd_v2
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        # (권장) Dialect 명시해두면 연결 실패 시에도 에러로그가 깔끔
        SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
        # 필요시 JPA 설정
        # SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      depends_on:
        postgres:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 20s
      restart: unless-stopped
      env_file:
        - ./.env
      expose:
        - "8080"    # 내부에서만 사용 (Caddy가 붙음)
  caddy:
    image: caddy:2-alpine
    container_name: employee_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  pg_data:
  caddy_data:
  caddy_config:
