@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZUlkIjo0LCJzaG9wSWQiOjMsInJvbGUiOiJlbXBsb3llZSIsImlhdCI6MTc1MDc4MTMzMCwiZXhwIjoxNzUwNzgyMjMwfQ.VXhgp4CyXPUyX8Q9uD2TaKskDSSRxugP2rj6cX9Bg08
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZUlkIjoxLCJpYXQiOjE3NTA3Njk2MjEsImV4cCI6MTc1MTM3NDQyMX0.wM0vj8j_9c-3LnSKNTsLdXWdo3_OPGApxHX4ytVY1dk

### 1️⃣ 로그인 요청
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "name": "김철수",
  "phoneLast4": "5432"
}

### 2️⃣ Access Token 보호 API 요청 (토큰 복사해서 Bearer 넣기)
GET http://localhost:3001/api/admin-only
Authorization: Bearer {{accessToken}}

### 3️⃣ Refresh Token으로 Access Token 재발급
POST http://localhost:3001/api/auth/refresh
Content-Type: application/json

{
  "token": "{{refreshToken}}"
}

### 4️⃣ 로그아웃
POST http://localhost:3001/api/auth/logout
Content-Type: application/json

{
  "token": "{{refreshToken}}"
}
