name: Backend Deploy (main)

on:
  push:
    branches: ['main']
    paths:
      - 'backend/**'
  workflow_dispatch:

concurrency:
  group: deploy-backend-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH (backend only)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            set -e
            cd ${{ secrets.PROJECT_PATH }}
            export HEALTH_URL="${HEALTH_URL:-https://mydreamday.shop/api/health}"
            chmod +x scripts/deploy.sh || true
            ./scripts/deploy.sh
